/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaseButton: typeof import('./src/components/button/BaseButton.vue')['default']
    BaseCheckbox: typeof import('./src/components/checkbox/BaseCheckbox.vue')['default']
    BaseCheckboxGroup: typeof import('./src/components/checkbox/BaseCheckboxGroup.vue')['default']
    BaseDialog: typeof import('./src/components/dialog/BaseDialog.vue')['default']
    BaseInput: typeof import('./src/components/input/BaseInput.vue')['default']
    BaseRadio: typeof import('./src/components/radio/BaseRadio.vue')['default']
    BaseTable: typeof import('./src/components/table/BaseTable.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElMain: typeof import('element-plus/es')['ElMain']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
